# Generated by Django 5.2.10 on 2026-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('seller_rating', models.FloatField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
